### ISSUE TITLE
Receiving wrong longitude value

### ISSUE THREAD

**Issue by quietlychris** [MechanicalPython/adafruit_gps#2]
Hello,

I'm trying to parse some data from the Adafruit Ultimate GPS through a USB serial connection, on a Raspberry Pi. For the most part things, have worked out as expected, except I'm getting a very odd number for my longitude value. 

I'm comparing the other results (HDOP, etc.) against the output using the recommended Python [script](https://learn.adafruit.com/adafruit-ultimate-gps/circuitpython-python-uart-usage), as well as just knowing my current lat/long. 

My output through the Adafruit script, showing my correct lat/long (well, a slightly modified version so my current address isn't on the Internet) produces 
```
Fix timestamp: 10/29/2020 19:55:53
Latitude: 34.5 degrees
Longitude: -119.5 degrees
```
while this crate produces
```
Lat:34.5, Long:-26.8, Sats:8, MSL Alt:-12.7    // (again, slightly modified on the lat,long results in the decimal places)
PDOP:1.41, VDOP:0.89, HDOP:1.09
```

In this case, my compiler version is 1.47-stable (2020-10-07) compiling using `adafruit_gps = "0.3.6"` in my Cargo.toml file, using the `simple.rs` example. The same results have been produced on both `x86` and `armv7` architectures. I've also tested and reproduced this behaviour against the current `master` branch in this repository, which produces the same results. Any thoughts on what I might be able to change to get the correct output for the longitude value? Thanks for your time!

**Comment by chakflying** [comment]
Might be too late, but I found that the longitude is parsed incorrectly because it has 3 digits. I made a simple fix by checking if the input is long or short. You can replace lines in `src/nmea.rs:47`:

```rust
let deg: f32 = if degrees.len() == 9 { (&degrees[0..2]).parse::<f32>().unwrap() } else { (&degrees[0..3]).parse::<f32>().unwrap() };

let minutes: f32 = if degrees.len() == 9 { ((&degrees[2..]).parse::<f32>().unwrap()) / 60.0 } else { ((&degrees[3..]).parse::<f32>().unwrap()) / 60.0 };
```

**Comment by MechanicalPython** [comment]
Issue is (finally) fixed. Turned out that the NMEA format could be dddmm.mmmmm or ddmm.mmmmm and I have only accounted for the latter. It should now give correct longitude in either situation now.
